GET http://localhost:3000/users

###

GET http://localhost:3000/mflix/users/59b99db4cfa9a34dcd7885b6

###


POST  http://localhost:3000/mflix/users 
Content-Type: application/json

{
    "name":"parthibank",
    "email":"myemail.parthiban",
    "password":"password"
}

###
GET https://mflix-5cf1.onrender.com/users